# ANSI index mapping:
#  0: Black          8: Bright Black (Gray)
#  1: Red            9: Bright Red
#  2: Green         10: Bright Green
#  3: Yellow        11: Bright Yellow
#  4: Blue          12: Bright Blue
#  5: Magenta       13: Bright Magenta
#  6: Cyan          14: Bright Cyan
#  7: White         15: Bright White

# --- INPUT
export GUM_INPUT_PROMPT_FOREGROUND="4"
export GUM_INPUT_PROMPT_BACKGROUND=""
export GUM_INPUT_PLACEHOLDER_FOREGROUND="8"
export GUM_INPUT_PLACEHOLDER_BACKGROUND=""
export GUM_INPUT_CURSOR_FOREGROUND="5"
export GUM_INPUT_CURSOR_BACKGROUND=""
export GUM_INPUT_HEADER_FOREGROUND="6"
export GUM_INPUT_HEADER_BACKGROUND=""

# --- CHOOSE
export GUM_CHOOSE_CURSOR_FOREGROUND="5"
export GUM_CHOOSE_CURSOR_BACKGROUND=""
export GUM_CHOOSE_HEADER_FOREGROUND="6"
export GUM_CHOOSE_HEADER_BACKGROUND=""
export GUM_CHOOSE_ITEM_FOREGROUND="7"
export GUM_CHOOSE_ITEM_BACKGROUND=""
export GUM_CHOOSE_SELECTED_FOREGROUND="6"
export GUM_CHOOSE_SELECTED_BACKGROUND=""
export GUM_CHOOSE_CURSOR_PREFIX="◇ "
export GUM_CHOOSE_SELECTED_PREFIX="◆ "
export GUM_CHOOSE_UNSELECTED_PREFIX="◇ "

# --- CONFIRM
export GUM_CONFIRM_PROMPT_FOREGROUND="4"
export GUM_CONFIRM_PROMPT_BACKGROUND=""
export GUM_CONFIRM_SELECTED_FOREGROUND="0"
export GUM_CONFIRM_SELECTED_BACKGROUND="2"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="7"
export GUM_CONFIRM_UNSELECTED_BACKGROUND=""

# --- FILTER
export GUM_FILTER_INDICATOR_FOREGROUND="5"
export GUM_FILTER_INDICATOR_BACKGROUND=""
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND="2"
export GUM_FILTER_SELECTED_PREFIX_BACKGROUND=""
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND="8"
export GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND=""
export GUM_FILTER_HEADER_FOREGROUND="6"
export GUM_FILTER_HEADER_BACKGROUND=""
export GUM_FILTER_TEXT_FOREGROUND="7"
export GUM_FILTER_TEXT_BACKGROUND=""
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="7"
export GUM_FILTER_CURSOR_TEXT_BACKGROUND=""
export GUM_FILTER_MATCH_FOREGROUND="3"
export GUM_FILTER_MATCH_BACKGROUND=""
export GUM_FILTER_PROMPT_FOREGROUND="4"
export GUM_FILTER_PROMPT_BACKGROUND=""
export GUM_FILTER_PLACEHOLDER_FOREGROUND="8"
export GUM_FILTER_PLACEHOLDER_BACKGROUND=""

# --- WRITE
export GUM_WRITE_BASE_FOREGROUND="7"
export GUM_WRITE_BASE_BACKGROUND=""
export GUM_WRITE_CURSOR_FOREGROUND="5"
export GUM_WRITE_CURSOR_BACKGROUND=""
export GUM_WRITE_CURSOR_LINE_FOREGROUND="7"
export GUM_WRITE_CURSOR_LINE_BACKGROUND="8"
export GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND="8"
export GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND=""
export GUM_WRITE_LINE_NUMBER_FOREGROUND="8"
export GUM_WRITE_LINE_NUMBER_BACKGROUND=""
export GUM_WRITE_END_OF_BUFFER_FOREGROUND="8"
export GUM_WRITE_END_OF_BUFFER_BACKGROUND=""
export GUM_WRITE_HEADER_FOREGROUND="6"
export GUM_WRITE_HEADER_BACKGROUND=""
export GUM_WRITE_PLACEHOLDER_FOREGROUND="8"
export GUM_WRITE_PLACEHOLDER_BACKGROUND=""
export GUM_WRITE_PROMPT_FOREGROUND="5"
export GUM_WRITE_PROMPT_BACKGROUND=""

# --- SPIN
export GUM_SPIN_SPINNER="points" # dot|line|minidot|jump|pulse|points|globe|moon|monkey|meter|hamburger
export GUM_SPIN_SPINNER_FOREGROUND="5"
export GUM_SPIN_SPINNER_BACKGROUND=""
export GUM_SPIN_TITLE_FOREGROUND="7"
export GUM_SPIN_TITLE_BACKGROUND=""

# --- PAGER
export GUM_PAGER_FOREGROUND="7"
export GUM_PAGER_BACKGROUND=""
export GUM_PAGER_LINE_NUMBER_FOREGROUND="8"
export GUM_PAGER_LINE_NUMBER_BACKGROUND=""
export GUM_PAGER_MATCH_FOREGROUND="3"
export GUM_PAGER_MATCH_BACKGROUND=""
export GUM_PAGER_MATCH_HIGH_FOREGROUND="0"
export GUM_PAGER_MATCH_HIGH_BACKGROUND="3"
export GUM_PAGER_HELP_FOREGROUND="8"
export GUM_PAGER_HELP_BACKGROUND=""

# --- FILE
export GUM_FILE_CURSOR_FOREGROUND="5"
export GUM_FILE_CURSOR_BACKGROUND=""
export GUM_FILE_SYMLINK_FOREGROUND="6"
export GUM_FILE_SYMLINK_BACKGROUND=""
export GUM_FILE_DIRECTORY_FOREGROUND="4"
export GUM_FILE_DIRECTORY_BACKGROUND=""
export GUM_FILE_FILE_FOREGROUND="7"
export GUM_FILE_FILE_BACKGROUND=""
export GUM_FILE_PERMISSIONS_FOREGROUND="8"
export GUM_FILE_PERMISSIONS_BACKGROUND=""
export GUM_FILE_SELECTED_FOREGROUND="0"
export GUM_FILE_SELECTED_BACKGROUND="5"
export GUM_FILE_FILE_SIZE_FOREGROUND="8"
export GUM_FILE_FILE_SIZE_BACKGROUND=""
export GUM_FILE_HEADER_FOREGROUND="6"
export GUM_FILE_HEADER_BACKGROUND=""

# --- TABLE
export GUM_TABLE_BORDER_FOREGROUND="8"
export GUM_TABLE_BORDER_BACKGROUND=""
export GUM_TABLE_CELL_FOREGROUND="7"
export GUM_TABLE_CELL_BACKGROUND=""
export GUM_TABLE_HEADER_FOREGROUND="4"
export GUM_TABLE_HEADER_BACKGROUND=""
export GUM_TABLE_SELECTED_FOREGROUND="0"
export GUM_TABLE_SELECTED_BACKGROUND="5"

# --- LOG
export GUM_LOG_LEVEL_FOREGROUND="7"
export GUM_LOG_LEVEL_BACKGROUND=""
export GUM_LOG_TIME_FOREGROUND="8"
export GUM_LOG_TIME_BACKGROUND=""
export GUM_LOG_PREFIX_FOREGROUND="5"
export GUM_LOG_PREFIX_BACKGROUND=""
export GUM_LOG_MESSAGE_FOREGROUND="7"
export GUM_LOG_MESSAGE_BACKGROUND=""
export GUM_LOG_KEY_FOREGROUND="4"
export GUM_LOG_KEY_BACKGROUND=""
export GUM_LOG_VALUE_FOREGROUND="2"
export GUM_LOG_VALUE_BACKGROUND=""
export GUM_LOG_SEPARATOR_FOREGROUND="8"
export GUM_LOG_SEPARATOR_BACKGROUND=""
