# exec-once = [workspace 3 silent] program_name
# exec-once = brightnessctl set 1%

# Restart waybar to prevent ocassional race conditions from the workspace module
# trying to connect before the compositor's IPC is ready
exec-once = sh -c 'sleep 5 && omarchy-restart-waybar'

# Foot server for footclient
exec-once = foot --server

# Ensure plugins load on boot
# exec-once = hyprpm reload
