source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    color = $color
    path = ~/.config/omarchy/current/background
    blur_size = 5
    blur_passes = 1
    brightness = 0.36
    contrast = 0.88
    vibrancy = 0.051
    noise = 0.531
}

animations {
    enabled = true
}

input-field {
    size = 390, 86
    position = 0, -336
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    dots_spacing = 0.27

    rounding = 16
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
