# Change the default Omarchy look'n'feel

$activeBorderColor = rgba(33ccffAA) rgba(00ff99AA) 225deg
$inactiveBorderColor = rgba(595959ff)

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = -1
    gaps_out = 1
    border_size = 2

    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Round window corners
    rounding = 8
    rounding_power = 3

    shadow {
        enabled = true
        range = 6
        render_power = 1
        color = 0xee1a1a1a
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1
        special = true
        brightness = 0.55
        contrast = 0.88
        vibrancy = 0.083
        noise = 0.0135
    }
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 13 9
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor

    groupbar {
        font_size = 15
    }
}

animations {
    enabled = yes

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 3.7, almostLinear
    animation = borderangle, 0,
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 2.68, easeOutQuint, popin 84%
    animation = windowsOut, 1, 1.41, linear, popin 77%
    animation = fade, 1, 3.03, quick
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 3.88, easeInOutCubic
    animation = specialWorkspaceIn, 1, 5.64, easeOutQuint, slidevert 13%
    animation = specialWorkspaceOut, 1, 4.33, easeOutQuint, slidevert 6%
}

cursor {
  inactive_timeout = 5
}

misc {
  font_family = monospace
}
