plugin {
    dynamic-cursors {
        enabled = true
        mode = tilt
        threshold = 3

        tilt {
            limit = 3300
            function = linear
            window = 111
        }

        shake {
            enabled = false
        }
    }
}
