# Opacity
windowrule = opacity 1 1, match:class .*
# windowrule = opacity 1 0.85, match:class .*

# Floating windows rule
windowrule = size 1120 773, match:tag floating-window
# Floating btop rule
windowrule = tag +floating-btop, match:class (org.omarchy.btop)
windowrule = size 980 870, match:tag floating-btop
# normal steam
windowrule = float off, match:class steam

# Set scratchpad as scrolling
workspace = special:scratchpad, layout:scrolling

# Prevent Zed from forcing focus accross workspaces
windowrule = match:class ^(dev\.zed\.Zed)$, suppress_event activatefocus

# No closing terminals
# windowrule {
#   name = nocloser
#   match:initial_class = (com.mitchellh.ghostty|org.omarchy.nvim|foot|Alacritty)
#   no_close_for = 1000000000
# }

