[mgr]
show_hidden = true
sort_by = "mtime"
sort_reverse = true

[preview]
wrap = "yes"

[opener]
edit = [
  { run = 'nvim %s', block = true, desc = "Edit with Neovim" },
  { run = 'zed %s', orphan = true, desc = "Edit with Zed" },
]
image = [
  { run = 'imv %s', orphan = true, desc = "Open with imv" },
  { run = 'gthumb %s', orphan = true, desc = "Open with gthumb" },
  { run = 'gimp %s', orphan = true, desc = "Open with gimp" },
]

[open]
prepend_rules = [
  { mime = "application/json", use = "edit" },
  { mime = "application/javascript", use = "edit" },
  { mime = "application/toml", use = "edit" },
  { mime = "application/x-sh", use = "edit" },
  { mime = "application/wine-extension-ini", use = "edit" },

  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image" },

  { url = "*.json", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.yaml", use = "edit" },
  { url = "*.yml", use = "edit" },
  { url = "*.md",   use = "edit" },
  { url = "*.conf", use = "edit" },
  { url = "*.py",   use = "edit" },
  { url = "*.js",   use = "edit" },
  { url = "*.go",   use = "edit" },
  { url = "*.bash_history",   use = "edit" },
  { url = "*.python_history",   use = "edit" },
]
