# Higher GPU usage
# correct-downscaling=yes
# linear-downscaling=yes
# sigmoid-upscaling=yes

# Scaling (balanced for iGPU)
# scale=spline36
# cscale=spline36
# dscale=mitchell # faster

# Lower GPU
# video-sync=display-resample
# interpolation=no
# deband=no

# Video output (not really needed)
# vo=gpu-next
# profile=gpu-hq # "gpu-hq" or "fast"

# Hardware decoding
hwdec=vaapi
# hwdec-codecs=all

# Temporary fullscreen support to prevent washed-out colors
target-colorspace-hint=no

# Reproduction settings
loop-file=inf

# Limit integrated yt-dlp to 1080p
ytdl-format="best[height<=1080]"

# Cache
demuxer-max-bytes=30M
demuxer-max-back-bytes=30M

# Visualizer for audio files
[audio-only]
profile-cond=not video
lavfi-complex="[aid1]asplit[a1][ao];[a1]showfreqs=s=1280x720:mode=bar:r=25:ascale=sqrt:fscale=log:colors=#808080|#808080,format=yuv420p[vo]"
