add_newline = true
command_timeout = 200
format = """[$directory$git_status$git_branch]($style)
$character"""

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncate_to_repo = false
truncation_length = 0
format = "[$path]($style) "

[git_branch]
format = "[$branch]($style)"
style = "italic cyan"

[git_status]
format = ' [$all_status]($style) '
style = "cyan"
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = " "
staged = " "
renamed = " "
deleted = "󰵃 "
